# 0. Initialiseer - refresh external data en import libraries

### 0.1 De df_dim_sensor tabel bevat de volgende informatie
- **locatie**            = de naam van de locatie waar de sensor is geplaats
- **device_name**        = de naam van de sensor die op de label van de fysieke sensor staat
- **datum_geplaatst**      = de datum waarop de sensor in de grond is geplaatst
- **datum_weggehaald**  = de datum waarop de sensor uit de grond is gehaald. Als deze datum na vandaag ligt, dan zit de sensor daar nog in de grond.
- **diepte_plaatsing**     = de diepte waarop de pinnen van de sensor in de grond zijn geplaats (15cm of 30cm diep)
- **leeftijd_plant**     = de leeftijd van de beplanting waar de de sensor is geplaats (0-1, 1-2 of 2-3 jaar)
- **soort_plant**        = de omschrijving van de beplanting waar de sensor is geplaatst
- **locatie_regio**      = de regio van de stad waar de sensor is geplaatst
- **extra_omschrijving** = een extra omschrijving van de locatie waar de sensor is geplaatst (bijv. in de berm, vlakbij bestrating, ..)
- **old**                = voor start van nieuwe project zijn er al sensoren geplaatst, deze hebben de indicatie 'old'. Van deze data weten we niet hoe betrouwbaar deze is.
- **device_name_org**    = voor het koppelen van de device_id's met de device_name's is de originele (= org) benaming aangepast om de koppeling te vereenvoudigen, daarom voor de zekerheid deze kolom wel behouden.
- **device_id**          = de id van de device zoals deze geregistreerd staat in de quantified portal. Middels de device id's kan de data via de quantified API opgehaald worden.

### 0.2 De df_fact_sensor tabel bevat de volgende informatie
- **gateway_receive_time**  = tijdstip waarop sensor permittivity waarde is ontvangen
- **device**                = device_id waar de permittivity waarde vandaan komt
- **value**                 = de gemeten permittivity waarde

### 0.3 De df_KNMI bevat de volgende informatie
- **YYYYMMDD**  = Datum (YYYY=jaar MM=maand DD=dag)
- **FG**        = Etmaalgemiddelde windsnelheid (in 0.1 m/s)
- (**TG**        = Etmaalgemiddelde temperatuur (in 0.1 graden Celsius)) --> <u>vervangen door Zusterhof</u>
- **SQ**        = Zonneschijnduur (in 0.1 uur) berekend uit de globale straling (-1 voor <0.05 uur)
- **DR**        = Duur van de neerslag (in 0.1 uur)
- (**RH**        = Etmaalsom van de neerslag (in 0.1 mm) (-1 voor <0.05 mm)) --> <u>vervangen door Zusterhof</u>
- **PG**        = Etmaalgemiddelde luchtdruk herleid tot zeeniveau (in 0.1 hPa) berekend uit 24 uurwaarden
- **NG**        = Etmaalgemiddelde bewolking (bedekkingsgraad van de bovenlucht in achtsten, 9=bovenlucht onzichtbaar)
- **UG**        = Etmaalgemiddelde relatieve vochtigheid (in procenten)
- **EV24**      = Referentiegewasverdamping (Makkink) (in 0.1 mm)

### 0.4 De df_weerstation_leiden bevat de volgende informatie
- **datum**         = Datum meetwaarde
- **temperatuur**   = Etmaalgemiddelde temperatuur (in 0.1 graden Celsius)
- **neerslag**      = Etmaalsom van de neerslag (in mm) (-1 voor <0.05 mm)

### Notes
- De temperatuur en neerslag wordt van weerstation **Zusterhof** in Leiden gebruikt. De overige weerdata vanuit het KNMI van weerstation **Schiphol**.
- De KNMI data is ook op uurniveau beschikbaar, maar deze is niet geschikt voor de analyse vanwege datakwaliteit, daarom gebruiken we KNMI data op dagniveau.

In [4]:
# TODO:
# Stappenplan van acties voordat dit notebook gedraaid kan worden

In [5]:
# Import neccesary libraries
from logic_components.data_transformations import anonymize_location, resample
import numpy as np
import plotly.express as px

### 0. Refresh & Laad data:
- 1.1 Sensorinformatie vanuit google spreadsheet
- 1.2 Quantified data (= df_fact_sensor)
- 1.3 KNMI data (= df_KNMI)
- 1.4 Weerstation Leiden data (= df_weerstation_leiden)

In [6]:
# 0. Refresh & Laad data

refresh_quantify = True

if refresh_quantify:
    from api_components import refresh_quantified

from api_components import refresh_external_data
from api_components.data_loading import get_all_data

df_dim_sensor, df_fact_sensor, df_KNMI, df_weerstation_leiden = get_all_data()

Token: 51d99207bd9e08657147bd8662a2313062e4a72d6870393109987df15e13fe12
device: 93, count measures: 0
device: 54, count measures: 0
device: 193, count measures: 0
device: 208, count measures: 0
device: 356, count measures: 1
device: 360, count measures: 0
device: 361, count measures: 1
device: 362, count measures: 0
device: 369, count measures: 1
device: 395, count measures: 1
device: 372, count measures: 0
device: 400, count measures: 0
device: 401, count measures: 0
device: 396, count measures: 0
device: 397, count measures: 0
device: 399, count measures: 0
device: 404, count measures: 1
device: 405, count measures: 0
device: 408, count measures: 0
device: 410, count measures: 0
device: 414, count measures: 0
device: 415, count measures: 0
device: 416, count measures: 1
device: 418, count measures: 0
device: 113, count measures: 0
device: 112, count measures: 0
device: 93, count measures: 0
device: 54, count measures: 0
device: 193, count measures: 0
device: 208, count measures: 0
device: 356, count measures: 1
device: 360, count measures: 1
device: 361, count measures: 1
device: 362, count measures: 0
device: 369, count measures: 1
device: 395, count measures: 1
device: 372, count measures: 0
device: 400, count measures: 0
device: 401, count measures: 0
device: 396, count measures: 0
device: 397, count measures: 0
device: 399, count measures: 0
device: 404, count measures: 0
device: 405, count measures: 0
device: 408, count measures: 0
device: 410, count measures: 0
device: 414, count measures: 0
device: 415, count measures: 1
device: 416, count measures: 1
device: 418, count measures: 0
device: 113, count measures: 0
device: 112, count measures: 0

### 1. Inspecteer data
- 1.1 Check data info, head and tail
- 1.2 Check data visuals

In [7]:
# 1.1 Check data info, head and tail

# df_dim_sensor
display(df_dim_sensor.info(5))
display(df_dim_sensor.head(5))
display(df_dim_sensor.tail(5))

# df_fact_sensor
display(df_fact_sensor.info(5))
display(df_fact_sensor.head(5))
display(df_fact_sensor.tail(5))

# df_KNMI
display(df_KNMI.info(5))
display(df_KNMI.head(5))
display(df_KNMI.tail(5))

# df_weerstation_leiden
display(df_weerstation_leiden.info(5))
display(df_weerstation_leiden.head(5))
display(df_weerstation_leiden.tail(5))

# 1.2 Check data visuals
df_visual = df_fact_sensor.copy()
df_visual.sort_values(by=['device', 'gateway_receive_time'], inplace=True)

# fig = px.line(df_visual, x='gateway_receive_time', y='value', color='device', title='Time Series of all devices',
#               labels={'value': 'Permittivity', 'gateway_receive_time': 'Time'},
#               line_group='device', hover_name='device')

# fig.show()

# cutt_off = df_visual['gateway_receive_time'].max() - DateOffset(months=2)
# fig = px.line(df_KNMI[df_KNMI['datum'] > cutt_off], x='datum', y='neerslag', title='Time Series of neerslag KNMI')

# fig.show()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   locatie            42 non-null     object
 1   device_name        42 non-null     object
 2   datum_geplaatst    42 non-null     datetime64[ns]
 3   datum_weggehaald   42 non-null     datetime64[ns]
 4   soort_plant        42 non-null     object
 5   leeftijd_plant     42 non-null     object
 6   diepte_plaatsing   42 non-null     object
 7   omgevingsfactoren  42 non-null     object
 8   locatie_regio      42 non-null     object
 9   old                42 non-null     object
 10  current_location   42 non-null     object
 11  device_name_org    42 non-null     object
 12  device_id          42 non-null     int64
dtypes: datetime64[ns](2), int64(1), object(10)
memory usage: 4.4+ KB

None

,locatie,device_name,datum_geplaatst,datum_weggehaald,soort_plant,leeftijd_plant,diepte_plaatsing,omgevingsfactoren,locatie_regio,old,current_location,device_name_org,device_id
0,Burggravenlaan (old)_15,FF1 0-0004,2022-01-28,2023-05-24,Plantenvak,> 1 jaar,15 cm,groen,Binnenstad,Yes,No,FF1 0-0004,93
1,Vijf meilaan (2)_30,FF1 0-0004,2023-07-04,2262-04-11,Plantenvak,0-1 jaar,30 cm,bestrating,Zuid,No,Yes,FF1 0-0004,93
2,Beethovenpark_30,FF1 0-0027,2023-07-04,2023-08-07,Plantenvak,0-1 jaar,30 cm,groen,Zuid,No,No,FF1 0-0027,54
3,Beethovenpark_15,FF1 0-0027,2023-08-07,2262-04-11,Plantenvak,0-1 jaar,15 cm,groen,Zuid,No,Yes,FF1 0-0027,54
4,Ijselmeerlaan berm (old)_15,FF1 0-0027,2022-01-28,2023-05-01,Heesters,> 1 jaar,15 cm,bestrating,Noord,Yes,No,FF1 0-0027,54

,locatie,device_name,datum_geplaatst,datum_weggehaald,soort_plant,leeftijd_plant,diepte_plaatsing,omgevingsfactoren,locatie_regio,old,current_location,device_name_org,device_id
37,Langegracht Politie_15,FF2 0-0191,2023-08-02,2262-04-11,Plant en boom,> 1 jaar,15 cm,bestrating,Binnenstad,No,Yes,FF2 0-0191,416
38,Arendshorst_30,FF2 0-0193,2023-08-02,2262-04-11,Boom,> 1 jaar,30 cm,groen,Noord,No,Yes,FF2 0-0193,418
39,Arendshorst (old)_30,FF2 0-0193,2023-07-04,2023-08-02,Boom,> 1 jaar,30 cm,groen,Noord,Yes,No,FF2 0-0193,418
40,Lakenplein (old)_10,NETA1.0-0030,2022-04-11,2023-08-02,Heesters,> 1 jaar,10 cm,groen,Binnenstad,Yes,No,NETA1.0-0030,112
41,Tasmanpark (2)_15,NETA1.0-0030,2023-08-07,2262-04-11,Plantenvak,> 1 jaar,15 cm,groen,Binnenstad,No,Yes,NETA1.0-0030,112

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73824 entries, 0 to 73823
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   gateway_receive_time  73824 non-null  datetime64[ns]
 1   device                73824 non-null  int64
 2   value                 73824 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 1.7 MB

None

  gateway_receive_time  device  value
0  2024-10-30 09:48:03     405  20.71
1  2024-10-30 09:13:11     361   7.59
2  2024-10-30 08:55:33     400  23.05
3  2024-10-30 08:41:27     397  11.73
4  2024-10-30 08:27:30     396  11.45

      gateway_receive_time  device  value
73819  2025-07-11 12:42:03     361   6.94
73820  2025-07-11 11:24:01     369   7.69
73821  2025-07-11 12:50:18     395   5.56
73822  2025-07-11 12:09:28     404   4.81
73823  2025-07-11 12:52:06     416   7.84

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27220 entries, 0 to 27219
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   datum             27220 non-null  datetime64[ns]
 1   windsnelheid      27220 non-null  int64
 2   temperatuur       27220 non-null  int64
 3   zonneschijn_duur  22776 non-null  float64
 4   neerslag_duur     18873 non-null  float64
 5   neerslag          19915 non-null  float64
 6   luchtdruk         27220 non-null  int64
 7   bewolking         27215 non-null  float64
 8   vochtigheid       27216 non-null  float64
 9   verdamping        13772 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(3)
memory usage: 2.1 MB

None

,datum,windsnelheid,temperatuur,zonneschijn_duur,neerslag_duur,neerslag,luchtdruk,bewolking,vochtigheid,verdamping
0,1951-01-01,87,12,NaN,NaN,NaN,9891,7.0,90.0,NaN
1,1951-01-02,41,13,NaN,NaN,NaN,9876,8.0,93.0,NaN
2,1951-01-03,21,3,NaN,NaN,NaN,10019,6.0,94.0,NaN
3,1951-01-04,77,12,NaN,NaN,NaN,10098,7.0,94.0,NaN
4,1951-01-05,87,48,NaN,NaN,NaN,10059,8.0,95.0,NaN

,datum,windsnelheid,temperatuur,zonneschijn_duur,neerslag_duur,neerslag,luchtdruk,bewolking,vochtigheid,verdamping
27215,2025-07-06,43,177,15.0,57.0,158.0,10056,8.0,89.0,13.0
27216,2025-07-07,55,160,67.0,11.0,13.0,10071,6.0,76.0,33.0
27217,2025-07-08,49,153,41.0,32.0,64.0,10147,7.0,79.0,28.0
27218,2025-07-09,28,186,132.0,0.0,-1.0,10211,6.0,63.0,50.0
27219,2025-07-10,23,195,89.0,0.0,0.0,10225,4.0,71.0,41.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   datum        1197 non-null   datetime64[ns]
 1   temperatuur  1197 non-null   float64
 2   neerslag     1197 non-null   float64
dtypes: datetime64[ns](1), float64(2)
memory usage: 28.2 KB

None

       datum  temperatuur  neerslag
0 2022-02-19          6.3       9.3
1 2022-02-20          8.1      22.2
2 2022-02-21          7.0       1.8
3 2022-02-22          7.8       1.5
4 2022-02-23          8.3       0.0

          datum  temperatuur  neerslag
1192 2025-07-05         19.2       2.7
1193 2025-07-06         17.9      18.6
1194 2025-07-07         17.1       0.0
1195 2025-07-08         15.6      14.7
1196 2025-07-09         19.0       0.0

In [8]:
df_fact_sensor

      gateway_receive_time  device  value
0      2024-10-30 09:48:03     405  20.71
1      2024-10-30 09:13:11     361   7.59
2      2024-10-30 08:55:33     400  23.05
3      2024-10-30 08:41:27     397  11.73
4      2024-10-30 08:27:30     396  11.45
...                    ...     ...    ...
73819  2025-07-11 12:42:03     361   6.94
73820  2025-07-11 11:24:01     369   7.69
73821  2025-07-11 12:50:18     395   5.56
73822  2025-07-11 12:09:28     404   4.81
73823  2025-07-11 12:52:06     416   7.84

[73824 rows x 3 columns]

In [9]:
latest_values = df_fact_sensor.merge(df_dim_sensor, how='left', left_on='device', right_on='device_id')
latest_values = latest_values.loc[latest_values.groupby('device')['gateway_receive_time'].idxmax()]
print(len(latest_values))

latest_values[['device_name_org','device','gateway_receive_time']].sort_values(by=['gateway_receive_time'], ascending=False)

26

       device_name_org  device gateway_receive_time
128628      FF2 0-0191     416  2025-07-11 12:52:06
128624      FF2 0-0147     395  2025-07-11 12:50:18
128621      FF2 0-0136     361  2025-07-11 12:42:03
128620      FF2 0-0131     356  2025-07-11 12:17:22
128626      FF2 0-0179     404  2025-07-11 12:09:28
128623      FF2 0-0144     369  2025-07-11 11:24:01
128564      FF2 0-0174     397  2025-07-11 11:11:39
128573      FF2 0-0189     414  2025-07-11 11:09:26
128577      FF2 0-0190     415  2025-07-11 08:08:30
128606      FF2 0-0193     418  2025-07-11 06:58:08
128560      FF2 0-0148     372  2025-07-11 06:57:38
128530      FF2 0-0137     362  2025-07-10 12:48:22
126053      FF2 0-0173     396  2025-07-02 18:37:43
120166      FF2 0-0135     360  2025-03-15 09:41:39
109694      FF2 0-0102     208  2025-01-17 13:25:42
116371      FF2 0-0171     400  2024-12-20 07:49:37
109556      FF2 0-0180     405  2024-11-01 20:59:15
7906      NETA1.0-0030     112  2024-08-26 08:40:57
16085       FF2 0-0176     399  2024-06-26 17:50:42
19382       FF1 0-0027      54  2024-06-02 01:50:17
25166       FF2 0-0172     401  2024-04-07 12:40:47
27408       FF2 0-0183     408  2024-03-21 05:34:10
34838       FF1 0-0004      93  2024-02-08 00:06:59
49816       FF2 0-0185     410  2023-11-24 12:21:42
88006              NaN     113  2023-02-16 09:20:01
95182              NaN     193  2022-09-01 10:46:00

### 2. Prepareer data
- 2.1 Filter oude locaties er uit
- 2.2 Koppel df_dim_sensor aan df_fact_sensor
- 2.3 Filter per locatie op begin datum plaatsing tot eind datum plaatsing. Locaties zonder einddatum krijgen datum in de toekomst, zodat alle data tot aan vandaag in de dataset zit.
- 2.4 Resample per locatie de tijdreekst op dagniveau. De sensoren geven meerdere sensorwaardes per dag (in principe elke 4 uur), maar dit gaat niet parallel over alle sensoren en voor elke sensor even consequent. Daarom wordt er per dag een gemiddelde, min en max waarde berekend. Daar gaan we de analyse mee doen. De tijdbox functie (add_6H_timebox) gebruiken we momenteel niet, omdat we op dagniveau gaan kijken. Mochten we goede weerdata en sensordata op (4-)uurniveau hebben, dan zouden we ook op een lagere datum_tijd granulariteit analyses kunnen doen.
- 2.5 Prepareer weerdata. De temperatuur en neerslag wordt van weerstation **Zusterhof** in Leiden gebruikt. De overige weerdata vanuit het KNMI van weerstation **Schiphol**. Wanneer de data uit Zusterhof NaN values bevat, wordt deze vervangen door data vanuit het KNMI. **Let op**: we vervangen de negatieve neerslagwaarden (-1) door 0. KNMI maakt onderscheid tussen 'geen regen' (= 0) en 'bijna geen regen' (= -1). In ons geval zien we 'bijna geen' regen als 'geen regen' 
- 2.6 Koppel weerdata aan sensordata
- 2.7 Toevoegen van berekende kolommen

In [10]:
# 2.1 Filter oude locaties er uit
df_dim_sensor = df_dim_sensor[df_dim_sensor['old'] == 'No']
df_dim_sensor.head()

,locatie,device_name,datum_geplaatst,datum_weggehaald,soort_plant,leeftijd_plant,diepte_plaatsing,omgevingsfactoren,locatie_regio,old,current_location,device_name_org,device_id
1,Vijf meilaan (2)_30,FF1 0-0004,2023-07-04,2262-04-11,Plantenvak,0-1 jaar,30 cm,bestrating,Zuid,No,Yes,FF1 0-0004,93
2,Beethovenpark_30,FF1 0-0027,2023-07-04,2023-08-07,Plantenvak,0-1 jaar,30 cm,groen,Zuid,No,No,FF1 0-0027,54
3,Beethovenpark_15,FF1 0-0027,2023-08-07,2262-04-11,Plantenvak,0-1 jaar,15 cm,groen,Zuid,No,Yes,FF1 0-0027,54
6,Vijf meilaan (1)_15,FF2 0-0102,2023-07-13,2262-04-11,Plantenvak,0-1 jaar,15 cm,bestrating,Zuid,No,Yes,FF2 0-0102,208
7,Boshuizerkade_30,FF2 0-0131,2023-07-04,2262-04-11,Plantenvak,0-1 jaar,30 cm,bebouwing,Zuid,No,Yes,FF2 0-0131,356

In [11]:
# 2.2 Koppel df_dim_sensor aan df_fact_sensor
df = df_dim_sensor.merge(df_fact_sensor, how='left', left_on=[
                         'device_id'], right_on=['device']).drop(columns='device')

In [12]:
# 2.3 Filter per locatie op begin datum plaatsing tot eind datum plaatsing.

# Filter time series tussen 'datum_geplaatst' en 'datum_opgehaald'
df = df[(df['gateway_receive_time'] > df['datum_geplaatst']) &
        (df['gateway_receive_time'] < df['datum_weggehaald'])]
df.drop(columns=['device_id', 'datum_geplaatst',
        'datum_weggehaald'], inplace=True)

# Rename columns
df.columns = ['locatie', 'device_name', 'soort_plant', 'leeftijd_plant', 'diepte_plaatsing', 'extra_omschrijving', 'locatie_regio',
              'old', 'current_location', 'device_name_org', 'datum_tijd', 'meetwaarde']

# Verzamel locaties
locaties_lst = list(df['locatie'].unique())

# Inspecteer nieuwe dataset
display(df.info(5))
display(df.head(5))
display(df.tail(5))

<class 'pandas.core.frame.DataFrame'>
Index: 54409 entries, 0 to 78309
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   locatie             54409 non-null  object
 1   device_name         54409 non-null  object
 2   soort_plant         54409 non-null  object
 3   leeftijd_plant      54409 non-null  object
 4   diepte_plaatsing    54409 non-null  object
 5   extra_omschrijving  54409 non-null  object
 6   locatie_regio       54409 non-null  object
 7   old                 54409 non-null  object
 8   current_location    54409 non-null  object
 9   device_name_org     54409 non-null  object
 10  datum_tijd          54409 non-null  datetime64[ns]
 11  meetwaarde          54409 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(10)
memory usage: 5.4+ MB

None

,locatie,device_name,soort_plant,leeftijd_plant,diepte_plaatsing,extra_omschrijving,locatie_regio,old,current_location,device_name_org,datum_tijd,meetwaarde
0,Vijf meilaan (2)_30,FF1 0-0004,Plantenvak,0-1 jaar,30 cm,bestrating,Zuid,No,Yes,FF1 0-0004,2024-02-08 00:06:59,22.46
1,Vijf meilaan (2)_30,FF1 0-0004,Plantenvak,0-1 jaar,30 cm,bestrating,Zuid,No,Yes,FF1 0-0004,2024-02-03 07:46:46,21.63
2,Vijf meilaan (2)_30,FF1 0-0004,Plantenvak,0-1 jaar,30 cm,bestrating,Zuid,No,Yes,FF1 0-0004,2024-01-27 16:29:54,22.20
3,Vijf meilaan (2)_30,FF1 0-0004,Plantenvak,0-1 jaar,30 cm,bestrating,Zuid,No,Yes,FF1 0-0004,2023-12-25 22:11:39,25.36
4,Vijf meilaan (2)_30,FF1 0-0004,Plantenvak,0-1 jaar,30 cm,bestrating,Zuid,No,Yes,FF1 0-0004,2023-12-25 19:55:27,22.53

,locatie,device_name,soort_plant,leeftijd_plant,diepte_plaatsing,extra_omschrijving,locatie_regio,old,current_location,device_name_org,datum_tijd,meetwaarde
78305,Tasmanpark (2)_15,NETA1.0-0030,Plantenvak,> 1 jaar,15 cm,groen,Binnenstad,No,Yes,NETA1.0-0030,2023-11-12 05:42:53,18.41
78306,Tasmanpark (2)_15,NETA1.0-0030,Plantenvak,> 1 jaar,15 cm,groen,Binnenstad,No,Yes,NETA1.0-0030,2023-11-12 03:26:12,18.83
78307,Tasmanpark (2)_15,NETA1.0-0030,Plantenvak,> 1 jaar,15 cm,groen,Binnenstad,No,Yes,NETA1.0-0030,2023-11-11 13:54:11,18.94
78308,Tasmanpark (2)_15,NETA1.0-0030,Plantenvak,> 1 jaar,15 cm,groen,Binnenstad,No,Yes,NETA1.0-0030,2023-11-11 00:24:33,18.89
78309,Tasmanpark (2)_15,NETA1.0-0030,Plantenvak,> 1 jaar,15 cm,groen,Binnenstad,No,Yes,NETA1.0-0030,2023-11-10 16:34:59,18.62

In [13]:
# 2.4 Resample per locatie de tijdreekst op dagniveau.

# Resample time series op dagniveau
df_resample = df.set_index(['locatie', 'datum_tijd'])
resample_freq = 'D'  # '6H'

df = resample(df_resample, resample_freq)
df.columns = ['locatie', 'datum', 'min_meetwaarde',
              'max_meetwaarde', 'gem_meetwaarde']

df = df_dim_sensor[df_dim_sensor['locatie'].isin(locaties_lst)].merge(
    df, how='left', left_on=['locatie'], right_on=['locatie'])
df = df[(df['datum'] > df['datum_geplaatst']) &
        (df['datum'] < df['datum_weggehaald'])]

test = df.copy()

df = df[['locatie', 'diepte_plaatsing', 'leeftijd_plant', 'soort_plant', 'locatie_regio',
       'omgevingsfactoren', 'datum','min_meetwaarde', 'max_meetwaarde', 'gem_meetwaarde']]
       
df.head()

/Users/jspan/Library/CloudStorage/OneDrive-ilionxGroupBV/03 Projects/05 - Gemeente Leiden/leiden_water_in_the_cloud/src/logic_components/data_transformations.py:44: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[['min', 'max', 'mean']] = df[['min', 'max', 'mean']].fillna(method='ffill')

,locatie,diepte_plaatsing,leeftijd_plant,soort_plant,locatie_regio,omgevingsfactoren,datum,min_meetwaarde,max_meetwaarde,gem_meetwaarde
1,Vijf meilaan (2)_30,30 cm,0-1 jaar,Plantenvak,Zuid,bestrating,2023-07-05,21.56,44.42,33.196667
2,Vijf meilaan (2)_30,30 cm,0-1 jaar,Plantenvak,Zuid,bestrating,2023-07-06,37.69,40.46,38.710000
3,Vijf meilaan (2)_30,30 cm,0-1 jaar,Plantenvak,Zuid,bestrating,2023-07-07,35.07,37.54,36.231111
4,Vijf meilaan (2)_30,30 cm,0-1 jaar,Plantenvak,Zuid,bestrating,2023-07-08,33.61,35.65,34.257778
5,Vijf meilaan (2)_30,30 cm,0-1 jaar,Plantenvak,Zuid,bestrating,2023-07-09,32.45,34.34,33.321429

In [14]:
test[test['locatie'] == 'Bachstraat (1)_15']

,locatie,device_name,datum_geplaatst,datum_weggehaald,soort_plant,leeftijd_plant,diepte_plaatsing,omgevingsfactoren,locatie_regio,old,current_location,device_name_org,device_id,datum,min_meetwaarde,max_meetwaarde,gem_meetwaarde
5392,Bachstraat (1)_15,FF2 0-0148,2023-08-07,2262-04-11,Plantenvak,0-1 jaar,15 cm,bebouwing,Zuid,No,Yes,FF2 0-0148,372,2023-08-08,16.77,17.29,17.006667
5393,Bachstraat (1)_15,FF2 0-0148,2023-08-07,2262-04-11,Plantenvak,0-1 jaar,15 cm,bebouwing,Zuid,No,Yes,FF2 0-0148,372,2023-08-09,16.67,16.91,16.792500
5394,Bachstraat (1)_15,FF2 0-0148,2023-08-07,2262-04-11,Plantenvak,0-1 jaar,15 cm,bebouwing,Zuid,No,Yes,FF2 0-0148,372,2023-08-10,15.95,16.21,16.080000
5395,Bachstraat (1)_15,FF2 0-0148,2023-08-07,2262-04-11,Plantenvak,0-1 jaar,15 cm,bebouwing,Zuid,No,Yes,FF2 0-0148,372,2023-08-11,15.60,15.95,15.785000
5396,Bachstraat (1)_15,FF2 0-0148,2023-08-07,2262-04-11,Plantenvak,0-1 jaar,15 cm,bebouwing,Zuid,No,Yes,FF2 0-0148,372,2023-08-12,15.43,15.95,15.704000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6091,Bachstraat (1)_15,FF2 0-0148,2023-08-07,2262-04-11,Plantenvak,0-1 jaar,15 cm,bebouwing,Zuid,No,Yes,FF2 0-0148,372,2025-07-07,3.80,3.80,3.800000
6092,Bachstraat (1)_15,FF2 0-0148,2023-08-07,2262-04-11,Plantenvak,0-1 jaar,15 cm,bebouwing,Zuid,No,Yes,FF2 0-0148,372,2025-07-08,4.33,4.33,4.330000
6093,Bachstraat (1)_15,FF2 0-0148,2023-08-07,2262-04-11,Plantenvak,0-1 jaar,15 cm,bebouwing,Zuid,No,Yes,FF2 0-0148,372,2025-07-09,4.06,4.12,4.100000
6094,Bachstraat (1)_15,FF2 0-0148,2023-08-07,2262-04-11,Plantenvak,0-1 jaar,15 cm,bebouwing,Zuid,No,Yes,FF2 0-0148,372,2025-07-10,4.06,4.12,4.100000
6095,Bachstraat (1)_15,FF2 0-0148,2023-08-07,2262-04-11,Plantenvak,0-1 jaar,15 cm,bebouwing,Zuid,No,Yes,FF2 0-0148,372,2025-07-11,4.06,4.12,4.090000

In [15]:
# # 2.5 Prepareer weerdata
# df_weerdata = df_KNMI.merge(df_weerstation_leiden,
#                             how='left', left_on='datum', right_on='datum')

# # df_weerstation_leiden bevat soms NaN values, deze vervangen we door data uit KNMI
# df_weerdata['temperatuur'] = np.where(df_weerdata['temperatuur_y'].isna(
# ), df_weerdata['temperatuur_x']/10, df_weerdata['temperatuur_y'])
# df_weerdata['neerslag'] = np.where(df_weerdata['neerslag_y'].isna(
# ), df_weerdata['neerslag_x']/10, df_weerdata['neerslag_y'])
# df_weerdata.drop(columns=['temperatuur_x', 'temperatuur_y',
#                  'neerslag_x', 'neerslag_y'], inplace=True)

# # Replace -0.1 values met 0. KNMI maakt onderscheid tussen 'geen regen' (= 0) en 'bijna geen regen' (= -0.1). In ons geval zien we 'bijna geen' regen als 'geen regen' 
# df_weerdata.loc[df_weerdata['neerslag'] < 0, 'neerslag'] = 0

# df_weerdata

In [16]:
# Step 1: Filter df_KNMI to include only data after January 1, 2022
df_weerdata = df_KNMI[df_KNMI['datum'] > '2022-01-01']

# Step 2: Replace NaN values in 'temperatuur' and 'neerslag' columns
df_weerdata['temperatuur'] = np.where(df_weerdata['temperatuur'].isna(), 0, df_weerdata['temperatuur'] / 10)

df_weerdata['neerslag'] = np.where(df_weerdata['neerslag'].isna(), 0, df_weerdata['neerslag'] / 10)


# Step 3: Replace -0.1 values in 'neerslag' column with 0
df_weerdata.loc[df_weerdata['neerslag'] < 0, 'neerslag'] = 0

# Display the modified df_weerdata to user (this would be for testing in an actual use case)
df_weerdata.head()

/var/folders/3_/n5vy3f4s457_v705xh5_zx9w0000gn/T/ipykernel_11992/2901710040.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_weerdata['temperatuur'] = np.where(df_weerdata['temperatuur'].isna(), 0, df_weerdata['temperatuur'] / 10)
/var/folders/3_/n5vy3f4s457_v705xh5_zx9w0000gn/T/ipykernel_11992/2901710040.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_weerdata['neerslag'] = np.where(df_weerdata['neerslag'].isna(), 0, df_weerdata['neerslag'] / 10)

,datum,windsnelheid,temperatuur,zonneschijn_duur,neerslag_duur,neerslag,luchtdruk,bewolking,vochtigheid,verdamping
25934,2022-01-02,90,11.4,20.0,51.0,6.5,10101,7.0,85.0,3.0
25935,2022-01-03,85,9.4,30.0,0.0,0.0,10066,5.0,84.0,4.0
25936,2022-01-04,45,6.4,5.0,9.0,0.7,9977,7.0,84.0,2.0
25937,2022-01-05,88,5.5,15.0,45.0,3.5,10062,6.0,80.0,2.0
25938,2022-01-06,43,3.3,46.0,10.0,0.2,10165,5.0,84.0,4.0

In [17]:
# # Step 1: Filter df_KNMI to include only data after January 1, 2022
# df_KNMI_filtered = df_KNMI[df_KNMI['datum'] > '2022-01-01']

# # Step 2: Merge df_KNMI_filtered with df_weerstation_leiden on 'datum' column
# df_weerdata = df_KNMI_filtered.merge(df_weerstation_leiden, how='left', on='datum')

# # Step 3: Replace NaN values in 'temperatuur' and 'neerslag' columns
# # 'temperatuur_y' and 'neerslag_y' from 'df_weerstation_leiden', and 'temperatuur_x' and 'neerslag_x' from 'df_KNMI'
# df_weerdata['temperatuur'] = np.where(df_weerdata['temperatuur_y'].isna(),
#                                       df_weerdata['temperatuur_x'] / 10,
#                                       df_weerdata['temperatuur_y'])
# df_weerdata['neerslag'] = np.where(df_weerdata['neerslag_y'].isna(),
#                                    df_weerdata['neerslag_x'] / 10,
#                                    df_weerdata['neerslag_y'])

# # Step 4: Drop the unnecessary original columns
# df_weerdata.drop(columns=['temperatuur_x', 'temperatuur_y', 'neerslag_x', 'neerslag_y'], inplace=True)

# # Step 5: Replace -0.1 values in 'neerslag' column with 0
# df_weerdata.loc[df_weerdata['neerslag'] < 0, 'neerslag'] = 0

# # Display the modified df_weerdata to user (this would be for testing in an actual use case)
# df_weerdata.head()

In [18]:
#2.6 koppel weerdata aan sensordata
df = df.merge(df_weerdata)

# De locaties worden omgezet naar getallen, deze anonieme dataset wordt opgeslagen als 'dataframe.xlsx' 
# en kan worden gebruikt in ChatGPT code interpreter. 
# Daarna worden de locatienamen weer teruggezet naar hun oorspronkelijke namen.
anonymize_location(df)

df.head(5)

,locatie,diepte_plaatsing,leeftijd_plant,soort_plant,locatie_regio,omgevingsfactoren,datum,gem_meetwaarde,windsnelheid,temperatuur,zonneschijn_duur,neerslag_duur,neerslag,luchtdruk,bewolking,vochtigheid,verdamping
0,Vijf meilaan (2)_30,30 cm,0-1 jaar,Plantenvak,Zuid,bestrating,2023-07-05,33.196667,90,14.2,17.0,97.0,26.6,10074,8.0,87.0,14.0
1,Vijf meilaan (2)_30,30 cm,0-1 jaar,Plantenvak,Zuid,bestrating,2023-07-06,38.710000,45,17.0,120.0,0.0,0.0,10171,7.0,70.0,43.0
2,Vijf meilaan (2)_30,30 cm,0-1 jaar,Plantenvak,Zuid,bestrating,2023-07-07,36.231111,38,21.2,152.0,0.0,0.0,10189,2.0,56.0,55.0
3,Vijf meilaan (2)_30,30 cm,0-1 jaar,Plantenvak,Zuid,bestrating,2023-07-08,34.257778,29,24.8,135.0,0.0,0.0,10164,3.0,58.0,54.0
4,Vijf meilaan (2)_30,30 cm,0-1 jaar,Plantenvak,Zuid,bestrating,2023-07-09,33.321429,32,21.5,49.0,10.0,9.2,10188,8.0,78.0,32.0

In [19]:
df.rename(columns={'omgevingsfactoren': 'extra_omschrijving'}, inplace=True)
df.to_excel('./data/prepped_sensor_data.xlsx', index=False)
df.head(5)

,locatie,diepte_plaatsing,leeftijd_plant,soort_plant,locatie_regio,extra_omschrijving,datum,gem_meetwaarde,windsnelheid,temperatuur,zonneschijn_duur,neerslag_duur,neerslag,luchtdruk,bewolking,vochtigheid,verdamping
0,Vijf meilaan (2)_30,30 cm,0-1 jaar,Plantenvak,Zuid,bestrating,2023-07-05,33.196667,90,14.2,17.0,97.0,26.6,10074,8.0,87.0,14.0
1,Vijf meilaan (2)_30,30 cm,0-1 jaar,Plantenvak,Zuid,bestrating,2023-07-06,38.710000,45,17.0,120.0,0.0,0.0,10171,7.0,70.0,43.0
2,Vijf meilaan (2)_30,30 cm,0-1 jaar,Plantenvak,Zuid,bestrating,2023-07-07,36.231111,38,21.2,152.0,0.0,0.0,10189,2.0,56.0,55.0
3,Vijf meilaan (2)_30,30 cm,0-1 jaar,Plantenvak,Zuid,bestrating,2023-07-08,34.257778,29,24.8,135.0,0.0,0.0,10164,3.0,58.0,54.0
4,Vijf meilaan (2)_30,30 cm,0-1 jaar,Plantenvak,Zuid,bestrating,2023-07-09,33.321429,32,21.5,49.0,10.0,9.2,10188,8.0,78.0,32.0

In [20]:
df_KNMI.to_excel('./data/KNMI.xlsx', index=False)
df_KNMI.head(5)

,datum,windsnelheid,temperatuur,zonneschijn_duur,neerslag_duur,neerslag,luchtdruk,bewolking,vochtigheid,verdamping
0,1951-01-01,87,12,NaN,NaN,NaN,9891,7.0,90.0,NaN
1,1951-01-02,41,13,NaN,NaN,NaN,9876,8.0,93.0,NaN
2,1951-01-03,21,3,NaN,NaN,NaN,10019,6.0,94.0,NaN
3,1951-01-04,77,12,NaN,NaN,NaN,10098,7.0,94.0,NaN
4,1951-01-05,87,48,NaN,NaN,NaN,10059,8.0,95.0,NaN